### ISSUE TITLE
Do you have the scripts to convert fasttext vec to txt?

### ISSUE THREAD

**Issue by Jacklau9515** [DS3Lab/cognival#5]
Hi,

Would you please be so kind as to provide the script that converting fasttext vec to the txt files?

Many thanks!
Jack

**Comment by norahollenstein** [comment]
Hi Jack, 
we didn't write a script for this. The files are already raw text (just change the extension from .vec to .txt). We manually added the header (you can fin the format of the header in the readme), and split the files in to various chunks because of the memory issues.
