### ISSUE TITLE
What is the best prediction results of BERT embeddings in each EEG dataset?

### ISSUE THREAD

**Issue by Jacklau9515** [DS3Lab/cognival#6]
Hi,
When I was trying to reproduce the results in Appendix B from the paper, however, I failed to reproduce the BERT word embeddings with cognitive data sources in all three modalities.

I was using the **standard_vocab.txt** (~/cognival-cli/user/resource/standard_vocab.txt) with the pre-trained BERT-base/large models that downloaded from **embedding_registry.json** to extract the hidden states of the second to last (12/24) of output layers as the representation for every single token.

Assuming something is wrong when I was extracting the features from the BERT models, and would you be so kind as to provide more details about how did you generate the BERT word vectors or share the bert_base.txt and bert_large.txt which you used to generate the results in Appendix B from the paper if it is doable?

Btw, I ran the **binary_to_text_conversion.py** (~/cognival cli/cognival/handlers/binary_to_text_conversion.py)script to generate the best word vectors txt files.

Many thanks,
Jack

**Comment by norahollenstein** [comment]
Hi Jack,

We generated the BERT embeddings with the bert-service: https://github.com/hanxiao/bert-as-service
If you need our original embeddings, you can download them here: https://drive.google.com/open?id=1bWHfxDLEmIf6C09A_fuG6yEWaUimzSbS

As mentioned previously, please note that we found a few smaller bugs in our original code, for example, the vocabulary list was missing some words, etc. We have fixed all this and made the system much more robust with a nice command line interface. We recommend to use it from now on: https://github.com/DS3Lab/cognival-cli

Best,
Nora

**Comment by Jacklau9515** [comment]
> Hi Jack,
> 
> We generated the BERT embeddings with the bert-service: https://github.com/hanxiao/bert-as-service
> If you need our original embeddings, you can download them here: https://drive.google.com/open?id=1bWHfxDLEmIf6C09A_fuG6yEWaUimzSbS
> 
> As mentioned previously, please note that we found a few smaller bugs in our original code, for example, the vocabulary list was missing some words, etc. We have fixed all this and made the system much more robust with a nice command line interface. We recommend to use it from now on: https://github.com/DS3Lab/cognival-cli
> 
> Best,
> Nora

Hi Nora,

Thank you for your help, and I have successfully reproduced the [BERT-base, EEG] results from Appendix B in your paper. And I will use the new robust cognival system as you recommended.

However, the shared **bert_service_large.txt** is empty in **bert_elmo_cognival_original.zip** folder, so would you please share the BERT-Service-Large txt file as well?

Thanks again for your help!

Best,
Jack

**Comment by norahollenstein** [comment]
Sorry about that, I have replaced the file now. Please download the zip again :)

**Comment by Jacklau9515** [comment]
> Sorry about that, I have replaced the file now. Please download the zip again :)

Thanks Nora, and I have downloaded the updated zip folder. However, for **bert_service_large.txt**, it is still an empty file and just adds a header of the 1024 dimension. So would you please update it again as I m keen to reproduce the BERT related MSE results?

Best,
Jack

**Comment by norahollenstein** [comment]
Now it should really be there!

**Comment by Jacklau9515** [comment]
> Now it should really be there!

Yes, all good now, really thanks for your help, I appreciate it :)

**Comment by norahollenstein** [comment]
Of course :) Let me know if you run into any other issues or if you want to discuss the reproduced results.
